# Stage: Build
FROM ubuntu:18.04 


#AS build


# copy files for integration
#COPY . .

# Set up environment variables
ENV LC_ALL=C 

#  HOME="/gpfs/work/jacobb/data/SINGULARITY/SCHISM/"

# Update and install necessary dependencies
RUN apt-get update && apt-get install -y \
    netcat \
    gnupg curl \
    git \
    gfortran g++ \
    libnetcdf-dev libnetcdff-dev \
    libmpich-dev \
    make \
    python-minimal \
    python3-minimal \
    nano \
    vim \	
    wget \
    checkinstall

	
# Install cmake 3.20.0
RUN wget https://github.com/Kitware/CMake/releases/download/v3.20.0/cmake-3.20.0.tar.gz && \
    tar -zvxf cmake-3.20.0.tar.gz && \
    cd cmake-3.20.0 && \
    ./configure -- -DCMAKE_USE_OPENSSL=OFF && \
    ./bootstrap && \
    make -j8 && \
    checkinstall --pkgname=cmake --pkgversion="3.20-custom" --default && \
    hash -r

# Clone SCHISM repository
#RUN mkdir -p /gpfs/work/jacobb/data/SINGULARITY/SCHISM && \
#    git clone -b v5.11 --single-branch --depth=1 https://github.com/schism-dev/schism.git /SCHISM
RUN mkdir /SCHISM && \
git clone -b v5.11 --single-branch --depth=1 https://github.com/schism-dev/schism.git /SCHISM

# Configure SCHISM build
RUN cd /SCHISM && \
    ln -s cmake/SCHISM.local.ubuntu SCHISM.local.build && \
    mkdir GBconfig && cd GBconfig && \
    cmake -C ../cmake/SCHISM.local.build ../src -DTVD_LIM=SB -DCMAKE_Fortran_FLAGS=" -DPREC_EVAP=ON" -DPREC_EVAP=ON && \
    make all

# Add a custom entry script
RUN echo -e "cd /rundir\nSCHISM/GBconfig/bin/pschism_PREC_EVAP_TVD-SB 6" > /SCHISM/exec.sh && \
    chmod u+rwx /SCHISM/exec.sh

# Add labels
LABEL Author="benjamin.jacob@hereon.de" \
      Version="v0.0.1"

# Stage: Runtime
#FROM ubuntu:18.04

# Set environment variables
ENV LC_ALL=C \
    HOME="/gpfs/work/jacobb/data/SINGULARITY/SCHISM/"

# Copy files from the build stage
COPY --from=build /SCHISM /SCHISM

# Add files and directories
RUN mkdir -p /rundir/outputs

# Expose the listen port
#EXPOSE $LISTEN_PORT

# Add test command
RUN grep -q NAME=\"Ubuntu\" /etc/os-release || echo "Container base is not Ubuntu."

# Default command for running the container
#CMD ["bash", "-c", "echo 'Container was created'; echo 'schism is in'; cd /rundir; /SCHISM/GBconfig/bin/pschism_PREC_EVAP_TVD-SB 2"]
CMD ["bash", "-c", "echo 'Container was created'"]

# Add a start script
#ENTRYPOINT ["/bin/bash"]
##ENTRYPOINT ["nc", "-lp", "$LISTEN_PORT"]

