#!/bin/tcsh
#SBATCH --job-name=EUrunTest
#SBATCH --partition=pCluster
#SBATCH --nodes=20
#SBATCH --ntasks-per-node=48
#SBATCH --time=72:00:00   #72h max
#SBATCH --mail-type=FAIL
#SBATCH --account=KSD
#SBATCH --output=schism.o%j
#SBATCH --error=schism.e%j

module load compilers/intel/2019.4.243
module load intelmpi #/2019.3.199
module load netcdf/4.7.0
module load hdf5/1.10.5
module load pnetcdf/1.11.2

srun --mpi=pmi2 /gpfs/home/jacobb/git/schism-master/schismgotm3/bin/pschism_strand
